<?php
require_once __DIR__ . '/../includes/functions.php';
require_role('dosen');
$pageTitle = 'Materi & Pengumuman';
$pdo = db(); $dosen = current_dosen();
$stmt = $pdo->prepare("SELECT k.id, mk.kode, mk.nama mata_kuliah, k.nama_kelas FROM kelas k JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE k.dosen_id=? ORDER BY mk.kode"); $stmt->execute([$dosen['id']]); $kelasList = $stmt->fetchAll();
try {
    if (is_post()) {
        $kelasId = (int)$_POST['kelas_id']; $cek=$pdo->prepare("SELECT id FROM kelas WHERE id=? AND dosen_id=?"); $cek->execute([$kelasId,$dosen['id']]); if (!$cek->fetch()) throw new RuntimeException('Kelas tidak valid.');
        if (($_POST['action'] ?? '') === 'materi') {
            $file = upload_file('file','materi',['pdf','doc','docx','ppt','pptx']) ?: null;
            $pdo->prepare("INSERT INTO materi (kelas_id,dosen_id,judul,tipe,file_path,link_url,deskripsi) VALUES (?,?,?,?,?,?,?)")
                ->execute([$kelasId,$dosen['id'],trim($_POST['judul']),$_POST['tipe'],$file,trim($_POST['link_url'] ?? ''),trim($_POST['deskripsi'] ?? '')]);
            set_flash('success','Materi berhasil ditambahkan.');
        } elseif (($_POST['action'] ?? '') === 'pengumuman') {
            $pdo->prepare("INSERT INTO pengumuman (kelas_id,dosen_id,judul,isi) VALUES (?,?,?,?)")->execute([$kelasId,$dosen['id'],trim($_POST['judul']),trim($_POST['isi'])]);
            set_flash('success','Pengumuman berhasil dibuat.');
        }
        redirect('dosen/materi.php');
    }
} catch (Throwable $e) { set_flash('danger',$e->getMessage()); redirect('dosen/materi.php'); }
$stmt = $pdo->prepare("SELECT m.*, mk.nama mata_kuliah, k.nama_kelas FROM materi m JOIN kelas k ON k.id=m.kelas_id JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE m.dosen_id=? ORDER BY m.created_at DESC"); $stmt->execute([$dosen['id']]); $materi=$stmt->fetchAll();
$stmt = $pdo->prepare("SELECT p.*, mk.nama mata_kuliah, k.nama_kelas FROM pengumuman p JOIN kelas k ON k.id=p.kelas_id JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE p.dosen_id=? ORDER BY p.created_at DESC LIMIT 20"); $stmt->execute([$dosen['id']]); $pengumuman=$stmt->fetchAll();
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/sidebar.php';
?>
<div class="row g-3 mb-3"><div class="col-lg-7"><div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Upload Materi</div><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="action" value="materi"><div class="col-md-6"><label class="form-label">Kelas</label><select name="kelas_id" class="form-select"><?php foreach ($kelasList as $k): ?><option value="<?= $k['id'] ?>"><?= e($k['kode'].' - '.$k['mata_kuliah'].' ('.$k['nama_kelas'].')') ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Tipe</label><select name="tipe" class="form-select"><option value="PDF">PDF/File</option><option value="Video">Link Video</option><option value="Website">Link Website</option></select></div><div class="col-12"><label class="form-label">Judul</label><input name="judul" class="form-control" required></div><div class="col-md-6"><label class="form-label">File</label><input type="file" name="file" class="form-control"></div><div class="col-md-6"><label class="form-label">Link</label><input name="link_url" class="form-control" placeholder="https://..."></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control"></textarea></div><div class="col-12"><button class="btn btn-primary">Simpan Materi</button></div></form></div></div></div><div class="col-lg-5"><div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Buat Pengumuman</div><div class="card-body"><form method="post" class="row g-3"><input type="hidden" name="action" value="pengumuman"><div class="col-12"><label class="form-label">Kelas</label><select name="kelas_id" class="form-select"><?php foreach ($kelasList as $k): ?><option value="<?= $k['id'] ?>"><?= e($k['kode'].' - '.$k['mata_kuliah'].' ('.$k['nama_kelas'].')') ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Judul</label><input name="judul" class="form-control" required></div><div class="col-12"><label class="form-label">Isi</label><textarea name="isi" class="form-control" required></textarea></div><div class="col-12"><button class="btn btn-primary">Kirim Pengumuman</button></div></form></div></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Materi Terunggah</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Materi</th><th>Kelas</th><th>Link/File</th></tr></thead><tbody><?php foreach ($materi as $m): ?><tr><td><div class="fw-semibold"><?= e($m['judul']) ?></div><small class="text-muted"><?= e($m['tipe'].' | '.$m['created_at']) ?></small></td><td><?= e($m['mata_kuliah'].' '.$m['nama_kelas']) ?></td><td><?php if ($m['file_path']): ?><a href="<?= base_url($m['file_path']) ?>" target="_blank">File</a><?php endif; ?><?php if ($m['link_url']): ?><a class="ms-2" href="<?= e($m['link_url']) ?>" target="_blank">Link</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-lg-5"><div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Pengumuman Terbaru</div><div class="card-body"><?php foreach ($pengumuman as $p): ?><div class="border-bottom pb-2 mb-2"><b><?= e($p['judul']) ?></b><br><small class="text-muted"><?= e($p['mata_kuliah'].' | '.$p['created_at']) ?></small><p class="mb-0"><?= e($p['isi']) ?></p></div><?php endforeach; ?><?php if (!$pengumuman): ?><p class="text-muted mb-0">Belum ada pengumuman.</p><?php endif; ?></div></div></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
