<?php
require_once __DIR__ . '/../includes/functions.php';
require_role('dosen');
$pageTitle = 'Tugas Online';
$pdo = db(); $dosen = current_dosen();
$stmt = $pdo->prepare("SELECT k.id, mk.kode, mk.nama mata_kuliah, k.nama_kelas FROM kelas k JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE k.dosen_id=? ORDER BY mk.kode"); $stmt->execute([$dosen['id']]); $kelasList = $stmt->fetchAll();
try {
    if (is_post()) {
        $kelasId=(int)$_POST['kelas_id']; $cek=$pdo->prepare("SELECT id FROM kelas WHERE id=? AND dosen_id=?"); $cek->execute([$kelasId,$dosen['id']]); if(!$cek->fetch()) throw new RuntimeException('Kelas tidak valid.');
        $file = upload_file('file','tugas',['pdf','doc','docx']) ?: null;
        $pdo->prepare("INSERT INTO tugas (kelas_id,dosen_id,judul,deskripsi,deadline,file_path) VALUES (?,?,?,?,?,?)")
            ->execute([$kelasId,$dosen['id'],trim($_POST['judul']),trim($_POST['deskripsi'] ?? ''),$_POST['deadline'],$file]);
        set_flash('success','Tugas berhasil dibuat.'); redirect('dosen/tugas.php');
    }
} catch(Throwable $e){ set_flash('danger',$e->getMessage()); redirect('dosen/tugas.php'); }
$stmt=$pdo->prepare("SELECT t.*, mk.kode, mk.nama mata_kuliah, k.nama_kelas, COUNT(p.id) jumlah_pengumpulan FROM tugas t JOIN kelas k ON k.id=t.kelas_id JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id LEFT JOIN pengumpulan_tugas p ON p.tugas_id=t.id WHERE t.dosen_id=? GROUP BY t.id ORDER BY t.deadline DESC"); $stmt->execute([$dosen['id']]); $tugas=$stmt->fetchAll();
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/sidebar.php';
?>
<div class="card shadow-sm mb-3"><div class="card-header bg-transparent fw-semibold">Buat Tugas</div><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-3"><div class="col-md-4"><label class="form-label">Kelas</label><select name="kelas_id" class="form-select"><?php foreach($kelasList as $k): ?><option value="<?= $k['id'] ?>"><?= e($k['kode'].' - '.$k['mata_kuliah'].' ('.$k['nama_kelas'].')') ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Judul</label><input name="judul" class="form-control" required></div><div class="col-md-4"><label class="form-label">Deadline</label><input type="datetime-local" name="deadline" class="form-control" required></div><div class="col-md-6"><label class="form-label">File Panduan</label><input type="file" name="file" class="form-control"></div><div class="col-md-6"><label class="form-label">Deskripsi</label><input name="deskripsi" class="form-control"></div><div class="col-12"><button class="btn btn-primary">Simpan Tugas</button></div></form></div></div>
<div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Daftar Tugas & Pengumpulan</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tugas</th><th>Kelas</th><th>Deadline</th><th>Pengumpulan</th></tr></thead><tbody><?php foreach($tugas as $t): ?><tr><td><div class="fw-semibold"><?= e($t['judul']) ?></div><small class="text-muted"><?= e($t['deskripsi']) ?></small></td><td><?= e($t['kode'].' - '.$t['mata_kuliah'].' '.$t['nama_kelas']) ?></td><td><?= e($t['deadline']) ?></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#sub<?= $t['id'] ?>"><?= e($t['jumlah_pengumpulan']) ?> pengumpulan</button></td></tr><tr class="collapse" id="sub<?= $t['id'] ?>"><td colspan="4"><?php $sub=$pdo->prepare("SELECT p.*,m.nim,m.nama FROM pengumpulan_tugas p JOIN mahasiswa m ON m.id=p.mahasiswa_id WHERE p.tugas_id=? ORDER BY p.submitted_at DESC"); $sub->execute([$t['id']]); $subs=$sub->fetchAll(); ?><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Mahasiswa</th><th>Waktu</th><th>File/Link</th><th>Catatan</th></tr></thead><tbody><?php foreach($subs as $s): ?><tr><td><?= e($s['nama'].' ('.$s['nim'].')') ?></td><td><?= e($s['submitted_at']) ?></td><td><?php if($s['file_path']): ?><a href="<?= base_url($s['file_path']) ?>" target="_blank">File</a><?php endif; ?><?php if($s['link_url']): ?><a class="ms-2" href="<?= e($s['link_url']) ?>" target="_blank">Link</a><?php endif; ?></td><td><?= e($s['catatan']) ?></td></tr><?php endforeach; ?><?php if(!$subs): ?><tr><td colspan="4" class="text-muted text-center">Belum ada pengumpulan.</td></tr><?php endif; ?></tbody></table></div></td></tr><?php endforeach; ?><?php if(!$tugas): ?><tr><td colspan="4" class="text-center text-muted py-4">Belum ada tugas.</td></tr><?php endif; ?></tbody></table></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
