<?php
require_once __DIR__ . '/../includes/functions.php';
require_role('mahasiswa');
$pageTitle = 'Rekap Absensi';
$mhs = current_mahasiswa();
$stmt = db()->prepare("SELECT k.id kelas_id, mk.kode, mk.nama mata_kuliah, SUM(a.status='Hadir') hadir, SUM(a.status='Izin') izin, SUM(a.status='Sakit') sakit, SUM(a.status='Alfa') alfa, COUNT(a.id) total FROM absensi a JOIN kelas k ON k.id=a.kelas_id JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE a.mahasiswa_id=? GROUP BY k.id ORDER BY mk.nama");
$stmt->execute([$mhs['id']]); $rekap = $stmt->fetchAll();
$stmt = db()->prepare("SELECT a.*, mk.nama mata_kuliah FROM absensi a JOIN kelas k ON k.id=a.kelas_id JOIN mata_kuliah mk ON mk.id=k.mata_kuliah_id WHERE a.mahasiswa_id=? ORDER BY a.tanggal DESC,a.pertemuan DESC LIMIT 50");
$stmt->execute([$mhs['id']]); $detail = $stmt->fetchAll();
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/sidebar.php';
?>
<div class="row g-3 mb-3"><?php foreach ($rekap as $r): $persen = $r['total'] ? round($r['hadir']/$r['total']*100,1) : 0; ?><div class="col-md-6 col-xl-4"><div class="card shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="fw-semibold"><?= e($r['kode'].' - '.$r['mata_kuliah']) ?></div><small class="text-muted">Total <?= e($r['total']) ?> pertemuan</small></div><span class="badge <?= $persen < 80 ? 'text-bg-danger' : ($persen < 85 ? 'text-bg-warning' : 'text-bg-success') ?> align-self-start"><?= e($persen) ?>%</span></div><div class="progress my-3" role="progressbar"><div class="progress-bar" style="width: <?= $persen ?>%"></div></div><small>Hadir <?= e($r['hadir']) ?>, Izin <?= e($r['izin']) ?>, Sakit <?= e($r['sakit']) ?>, Alfa <?= e($r['alfa']) ?></small><?php if ($persen < 85): ?><div class="alert alert-warning mt-3 mb-0 py-2 small">Peringatan: kehadiran mendekati batas minimum 80%.</div><?php endif; ?></div></div></div><?php endforeach; ?><?php if (!$rekap): ?><div class="col-12"><div class="alert alert-info">Belum ada data absensi.</div></div><?php endif; ?></div>
<div class="card shadow-sm"><div class="card-header bg-transparent fw-semibold">Detail Absensi Terbaru</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tanggal</th><th>Pertemuan</th><th>Mata Kuliah</th><th>Status</th><th>Keterangan</th></tr></thead><tbody><?php foreach ($detail as $d): ?><tr><td><?= e($d['tanggal']) ?></td><td><?= e($d['pertemuan']) ?></td><td><?= e($d['mata_kuliah']) ?></td><td><?= status_badge($d['status']) ?></td><td><?= e($d['keterangan']) ?></td></tr><?php endforeach; ?><?php if (!$detail): ?><tr><td colspan="5" class="text-center text-muted py-4">Belum ada absensi.</td></tr><?php endif; ?></tbody></table></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
